<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-CA" lang="en-CA">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>%%TITLE%%</title>
<link href="${ROOT}/style/icon.ico" rel="shortcut icon" type="image/x-icon" />
<link href="${ROOT}/style/disqus.css" media="all" rel="stylesheet" type="text/css" />
</head>
<body>

