<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-CA" lang="en-CA">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>%%TITLE%%</title>
<meta name="keywords" content="ieee communications society, ieee, comsoc, communications, telecommunications,
 wireless, optical, telecom, research, electronics, electrical engineering, networking, tutorials, conferences,
 fiber, standards, journals, magazines, books, education, ip, Network, LTE, RF, DySPAN" />
<meta name="copyright" content="Copyright &copy; 2011 IEEE Communications Society" />
<link href="${ROOT}/style/icon.ico" rel="shortcut icon" type="image/x-icon" />
<link href="${ROOT}/style/all.css" media="all" rel="stylesheet" type="text/css" />
<link href="${ROOT}/style/screen.css" media="screen" rel="stylesheet" type="text/css" />
<link href="${ROOT}/style/print.css" media="print" rel="stylesheet" type="text/css" />
<!--script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-29048176-1']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script-->
<script type="text/javascript" src="${ROOT}/style/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="${ROOT}/style/jquery.bpopup-0.7.0.min.js"></script>
<script type="text/javascript" src="${ROOT}/style/script.js"></script>
</head>
<body>

<div id="page-all">
<div id="page-header">&nbsp;</div>
<div id="page-menus">
<ul>
<li><a href="${ROOT}/">Tournaments</a></li>
<li><a href="${ROOT}/t/myteams">My Teams</a></li>
<li><a href="${ROOT}/seats">Seats</a></li>
${CURR_USER}
</ul>
</div>
<div id="page-content-wide">
<div id="page-content-main">

