<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN"
  "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en-CA" lang="en-CA">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />
<title>%%TITLE%%</title>
<link href="${ROOT}/style/icon.ico" rel="shortcut icon" type="image/x-icon" />
<link href="${ROOT}/style/all.css" media="all" rel="stylesheet" type="text/css" />
<link href="${ROOT}/style/screen.css" media="screen" rel="stylesheet" type="text/css" />
<link href="${ROOT}/style/print.css" media="print" rel="stylesheet" type="text/css" />
<script type="text/javascript">
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-18375354-4']);
  _gaq.push(['_trackPageview']);
  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
</script>
<script type="text/javascript" src="${ROOT}/style/jquery-1.7.2.min.js"></script>
<script type="text/javascript" src="${ROOT}/style/jquery.bpopup-0.7.0.min.js"></script>
<script type="text/javascript" src="${ROOT}/style/jquery.observehashchange-1.0.min.js"></script>
<script type="text/javascript" src="${ROOT}/style/script.js"></script>
</head>
<body>

<div id="page-all">
<div id="page-header">&nbsp;</div>
<div id="page-menus">
<ul class="user">
${CURR_USER}
</ul>
<ul>
<li><a href="${ROOT}/">Home</a></li>
<li><a href="${ROOT}/tournaments#">Tournaments</a></li>
<li><a href="${ROOT}/seats">Seats</a></li>
<li><a href="${ROOT}/prizes">Prizes</a></li>
<li><a href="http://www.battleroyale.ca/br6/">--Main Website--</a></li>
</ul>
</div>
<div id="page-content-wide">
<div id="page-content-main">

